name: CMake

on:
  push:
    branches: [ nncase ]
  pull_request:
    branches: [ nncase ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        include:
          - os: ubuntu-18.04
            bitness: 64
          - os: macos-10.15
            bitness: 64

    steps:
    - uses: actions/checkout@v2

    - name: Install cibuildwheel
      shell: bash
      run: python -m pip install cibuildwheel==2.0.1

    - name: Build wheels
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt install gcc-10 g++-10
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
        sudo apt-get install libegl1-mesa-dev -y
        sudo apt-get install libprotobuf-dev libleveldb-dev libsnappy-dev libopencv-dev libhdf5-serial-dev protobuf-compiler -y
        sudo apt-get install --no-install-recommends libboost-all-dev -y
        sudo apt-get install libopenblas-dev liblapack-dev libatlas-base-dev -y
        sudo apt-get install libgflags-dev libgoogle-glog-dev liblmdb-dev -y
        pip install numpy==1.19.2
        sudo unlink /usr/lib/x86_64-linux-gnu/libboost_python.so
        sudo ln -s /usr/lib/x86_64-linux-gnu/libboost_python-py36.so /usr/lib/x86_64-linux-gnu/libboost_python.so
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUSE_OPENCV=OFF
        cd ${{github.workspace}}/build && sudo make all && sudo make pycaffe

        cd ${{github.workspace}}/python && mkdir wheelhouse
        python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_PLATFORM: "linux"
        CIBW_BUILD: "cp37-*"
        CIBW_ARCHS_LINUX: "x86_64"
        CIBW_REPAIR_WHEEL_COMMAND: ""

    - name: Build wheels
      if: runner.os == 'Macos'
      shell: bash
      run: |
        brew install -vd snappy leveldb gflags glog szip lmdb
        brew install hdf5 openblas
        brew install -vd protobuf
        brew install -vd boost boost-python3
        pip install numpy==1.17.5
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUSE_OPENCV=OFF
        cd ${{github.workspace}}/build && sudo make all && sudo make pycaffe

        cd ${{github.workspace}}/python && mkdir wheelhouse
        python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_PLATFORM: "macos"
        CIBW_BUILD: "cp39-*"
        CIBW_ARCHS_MACOS: "x86_64"
        CIBW_REPAIR_WHEEL_COMMAND: ""
        CIBW_ENVIRONMENT: MACOSX_DEPLOYMENT_TARGET=10.15

    - name: Upload a Build Artifact
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v2.2.2
      with:
        name: warpctc-caffe-linux
        path: ./python/wheelhouse/*.whl
        if-no-files-found: error

    - name: Upload a Build Artifact
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v2.2.2
      with:
        name: libcaffe-linux
        path: ${{github.workspace}}/build/lib/libcaffe.so.1.0.0
        if-no-files-found: error

    - name: Upload a Build Artifact
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v2.2.2
      with:
        name: caffe-linux
        path: ${{github.workspace}}/build/lib/_caffe.so
        if-no-files-found: error

    - name: Upload a Build Artifact
      if: runner.os == 'Macos'
      uses: actions/upload-artifact@v2.2.2
      with:
        name: warpctc-caffe-macos
        path: ./python/wheelhouse/*.whl
        if-no-files-found: error

    - name: Upload a Build Artifact
      if: runner.os == 'Macos'
      uses: actions/upload-artifact@v2.2.2
      with:
        name: libcaffe-macos
        path: ${{github.workspace}}/build/lib/libcaffe.1.0.0.dylib
        if-no-files-found: error

    - name: Upload a Build Artifact
      if: runner.os == 'Macos'
      uses: actions/upload-artifact@v2.2.2
      with:
        name: caffe-macos
        path: ${{github.workspace}}/build/lib/_caffe.dylib
        if-no-files-found: error
