name: CMake

on:
  push:
    branches: [ nncase ]
  pull_request:
    branches: [ nncase ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            bitness: 64
          # - os: macos-10.15
          #   bitness: 64

    steps:
    - uses: actions/checkout@v2

    - name: Install cibuildwheel
      shell: bash
      run: pip install cibuildwheel

    - name: Build wheels
      if: runner.os == 'Linux'
      env:
        CIBW_ARCHS: "x86_64"
        CIBW_PLATFORM: "linux"
        CIBW_BUILD: "cp37-*"
        CIBW_REPAIR_WHEEL_COMMAND: ""
        CIBW_MANYLINUX_X86_64_IMAGE: "manylinux_2_24"
        CIBW_BEFORE_BUILD:
          "python --version && apt-get update &&
          apt install gcc-10 g++-10 &&
          update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100 &&
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 &&
          apt-get install libegl1-mesa-dev -y &&
          apt-get install libprotobuf-dev libleveldb-dev libsnappy-dev libopencv-dev libhdf5-serial-dev protobuf-compiler -y &&
          apt-get install --no-install-recommends libboost-all-dev -y &&
          apt-get install libopenblas-dev liblapack-dev libatlas-base-dev -y &&
          apt-get install libgflags-dev libgoogle-glog-dev liblmdb-dev -y &&
          apt-get install python3.7-dev &&
          update-alternatives --install /usr/bin/python python /usr/bin/python3.7 100 &&
          apt-get install python-pip &&
          pip install -U pip &&
          pip install numpy==1.19.2 &&
          unlink /usr/lib/x86_64-linux-gnu/libboost_python.so &&
          ln -s /usr/lib/x86_64-linux-gnu/libboost_python-py36.so /usr/lib/x86_64-linux-gnu/libboost_python.so &&
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUSE_OPENCV=OFF &&
          cd ${{github.workspace}}/build && make all && make pycaffe &&
          cd ${{github.workspace}}/python && mkdir wheelhouse &&
          update-alternatives --install /usr/bin/python python /usr/bin/python2.7 200"
      shell: bash
      run: |
        cd ${{github.workspace}}/python
        python -m cibuildwheel --output-dir wheelhouse

    - name: Build wheels
      if: runner.os == 'Macos'
      env:
        CIBW_ARCHS: "x86_64"
        CIBW_PLATFORM: "macos"
        CIBW_BUILD: "cp39-*"
        CIBW_REPAIR_WHEEL_COMMAND: ""
        CIBW_ENVIRONMENT: MACOSX_DEPLOYMENT_TARGET=10.15
        CIBW_BEFORE_BUILD:
          "brew install -vd snappy leveldb gflags glog szip lmdb &&
          brew install hdf5 openblas &&
          brew install -vd protobuf &&
          brew install -vd boost boost-python3 &&
          brew install python@3.9 &&
          pip install -U pip &&
          pip install numpy==1.16.6 &&
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUSE_OPENCV=OFF &&
          cd ${{github.workspace}}/build && make all && make pycaffe &&
          cd ${{github.workspace}}/python && mkdir wheelhous &&
          brew uninstall python@3.9"
      shell: bash
      run: |
        cd ${{github.workspace}}/python
        python -m cibuildwheel --output-dir wheelhouse

    - name: Upload a Build Artifact
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v2.2.2
      with:
        name: warpctc-caffe-linux
        path: ${{github.workspace}}/python/wheelhouse/*.whl
        if-no-files-found: error

    - name: Upload a Build Artifact
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v2.2.2
      with:
        name: libcaffe-linux
        path: ${{github.workspace}}/build/lib/libcaffe.so.1.0.0
        if-no-files-found: error

    - name: Upload a Build Artifact
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v2.2.2
      with:
        name: caffe-linux
        path: ${{github.workspace}}/build/lib/_caffe.so
        if-no-files-found: error

    - name: Upload a Build Artifact
      if: runner.os == 'Macos'
      uses: actions/upload-artifact@v2.2.2
      with:
        name: warpctc-caffe-macos
        path: ${{github.workspace}}/python/wheelhouse/*.whl
        if-no-files-found: error

    - name: Upload a Build Artifact
      if: runner.os == 'Macos'
      uses: actions/upload-artifact@v2.2.2
      with:
        name: libcaffe-macos
        path: ${{github.workspace}}/build/lib/libcaffe.1.0.0.dylib
        if-no-files-found: error

    - name: Upload a Build Artifact
      if: runner.os == 'Macos'
      uses: actions/upload-artifact@v2.2.2
      with:
        name: caffe-macos
        path: ${{github.workspace}}/build/lib/_caffe.dylib
        if-no-files-found: error
